### PR TITLE
Add hyperlink parsing under pictures

### PR DESCRIPTION
**Pull request by ulziibuyan**
Hello @Progi1984, I added hyperlinks to pictures using PowerPoint. When I tried to read them using your awesome library, the hyperlinks were not showing up. Turns out, they were not being parsed. This PR adds support and actually extends #49. Please let me know what can I do to make this PR better. Thanks!

### CODE REVIEW

**Comment by Progi1984** [comment]
@ulziibuyan Thank you for your contribution. Could you update Changelog.md ? And the perfect thing, could you update the method [displayShapeInfo](https://github.com/PHPOffice/PHPPresentation/blob/develop/samples/Sample_Header.php#L373) for displaying hyperlink on images in Sample 12 ? Thanks

**Comment by Progi1984** [comment]
@ulziibuyan After that, I could merge it.

**Comment by ulziibuyan** [comment]
@Progi1984 I'm not sure what caused the build to fail only for PHP: 7.1. Any ideas? https://travis-ci.org/PHPOffice/PHPPresentation/builds/595205590

**Comment by Progi1984** [comment]
@ulziibuyan I reset the failed Travis test.

**Comment by Progi1984** [comment]
Thank you @ulziibuyan for your contribution.

**Pull request merged**
