### PR TITLE
Drop the support for HHVM

### LINKED ISSUE #543: Drop the support for HHVM

### PR DESCRIPTION
**Pull request by sunspikes**
Fixes #543 and the develop build.

### CODE REVIEW

**Comment by Progi1984** [comment]
@sunspikes Thank you for your contribution. A small change before merge: Could you update the changelog.md file ? Thanks

**Comment by sunspikes** [comment]
@Progi1984 Done, can you please check if it's ok ?

**Comment by Progi1984** [comment]
@sunspikes Perfect

**Comment by sunspikes** [comment]
thank you!!

**Pull request merged**
