### PR TITLE
Fix bug : The animation is applied to the shape which is next to the…

### PR DESCRIPTION
**Pull request by shannan1989**
The animation is applied to the shape which is next to the target shape.
The id "1" is used for the slide itself. So when writing the animations AND shapes it's important to start the shapeId at 2. 
In PptSlides.php, when writing the shapes, the shapeId is starting at 0 by default and then pre-incrementing to 1. 
It needs to start at 1 to pre-increment to 2 for the first shape.

### CODE REVIEW

**Comment by Progi1984** [comment]
@shannan1989  Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

**Comment by Progi1984** [comment]
Please check at #531

**Comment by shannan1989** [comment]
> @shannan1989 Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

Done.

**Comment by Progi1984** [comment]
Superseeded by #783

**Pull request closed without merging**
