### PR TITLE
修改Paragraphs错位和模板图片引用问题

### PR DESCRIPTION
**Pull request by dzchen**

### CODE REVIEW

**Comment by Progi1984** [comment]
Translation of the title : Modify Paragraphs misplacement and template image reference issues

**Comment by Progi1984** [comment]
@dzchen  Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

**Comment by dzchen** [comment]
merge

**Comment by Progi1984** [comment]
Fixed in `develop` branch

**Pull request closed without merging**
