### PR TITLE
Fix #320

### LINKED ISSUE #320: Parsing text with different styles
Having the following :
```xml
<text:p text:style-name="P1">
I do 
<text:span text:style-name="T2">not</text:span>
 BASH
</text:p>
```
Only the content of `text:span` is returned for the paragraph.

Related : The text inside the paragraph is parsed only if there's no spans inside. https://github.com/PHPOffice/PHPPresentation/blob/develop/src/PhpPresentation/Reader/ODPresentation.php#L441L452

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/41885645-parsing-text-with-different-styles?utm_campaign=plugin&utm_content=tracker%2F323104&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F323104&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tcitworld**
Didn't manage to run the tests on the develop branch so I didn't add any, but please advise me !

Ref #320

### CODE REVIEW

**Comment by tcitworld** [comment]
Yeah, it's more complicated that this fix.

**Comment by tcitworld** [comment]
cc @Progi1984

**Comment by tcitworld** [comment]
ping @Progi1984

**Comment by Progi1984** [comment]
I work on it this week-end (this afternoon).

**Pull request merged**
