### PR TITLE
remove unneeded % signs to fix corruption when generating charts

### PR DESCRIPTION
**Pull request by jaek-s**
This is the same fix as in https://github.com/PHPOffice/PHPPresentation/pull/435, but it does not include any of the other changes. Its just the fix for charts.

### CODE REVIEW

**Comment by mhasanshahid** [comment]
You can review unit tests, for your all checks to pass.

**Comment by zhaoxinwei** [comment]
Thank you for solving my problem.But I came across a new problem that my chart could not be displayed on Microsoft PowerPoint2016.I hope you can help me

**Comment by mhasanshahid** [comment]
@zhaoxinwei try PR #435

**Comment by Progi1984** [comment]
@JAEK-S  Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

**Comment by Progi1984** [comment]
@jaek-s Is it ok for you ?

**Pull request closed without merging**
