### PR TITLE
PowerPoint2007 Reader : Load images in their initial format (and not by default in PNG)

### PR DESCRIPTION
**Pull request by polidog**
Load PowerPoint 2007 images converted all files to png.
It's only default used.
I'm changed mimeType and renderingFunction.

### CODE REVIEW

**Comment by Progi1984** [comment]
Hi @polidog, thank you for your contribution. Could you rebase your branch on develop ? Thanks.

**Comment by polidog** [comment]
@Progi1984 Why is rebase on develop? I'm changed base branch to develop. Is this all right?

**Comment by Progi1984** [comment]
@polidog Thanks for `develop`. Could you merge this PR https://github.com/polidog/PHPPresentation/pull/1 using "squash & merge " ?
image

**Comment by polidog** [comment]
@Progi1984 Thanks your PR. I'm marged done.

**Comment by Progi1984** [comment]
Thanks @polidog for your contribution.

**Pull request merged**
