### PR TITLE
fix other image mime type support

### PR DESCRIPTION
**Pull request by smithyj**
I found that other types of image drawing are not supported. so fix

### CODE REVIEW

**Comment by Progi1984** [comment]
@smithyj Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

**Comment by smithyj** [comment]
> @smithyj Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

o, I think I have deleted that branch, I will create new branch to PR

**Comment by Progi1984** [comment]
@smithyj Thanks

**Comment by Progi1984** [comment]
New PR #547

**Pull request closed without merging**
