### PR TITLE
Defining width & height of a shape don't return any error if width & height were equal to 0

### PR DESCRIPTION
**Pull request by surger**
Add zero check before divizion

### CODE REVIEW

**Comment by Progi1984** [comment]
Hi @surger, thank you for your contribution. Could you update the CHANGELOG.md and add a test in tests/PhpPresentation/Tests/Shape/AbstractGraphicTest.php before merge ? Thanks

**Comment by surger** [comment]
@Progi1984 Which version should I specify CHANGELOG.md? And my commit so little, you may miss my commit :).
And I don't think what my changes need test.
AbstractGraphicTest.php have enough tests for it.

**Comment by Progi1984** [comment]
@surger The next version is 0.10. No, each commit, each contribution is a part of next version.

Ok for no tests. You're right.

**Comment by Progi1984** [comment]
@surger Could you apply the same logic to the method setWidth ? And update Changelog.md 😉 After that I will merge it.

**Comment by Progi1984** [comment]
Thank you @surger for your contribution.

**Pull request merged**
