### PR TITLE
Shapes and fix for sample broken charts

### PR DESCRIPTION
**Pull request by mhasanshahid**
Shapes like arrow pointer, rectangle, triangle, and round rectangle has been added, In samples were given charts that are seems to be broken with this master branch, Changes have been made to fix all the given sample charts.

### CODE REVIEW

**Comment by Progi1984** [comment]
@mhasanshahid What a good job. Could you look at the log of Travis for fixing it before merge (PHPCS & PHPUnit)
https://travis-ci.org/PHPOffice/PHPPresentation/jobs/324072125

**Comment by mhasanshahid** [comment]
@Progi1984 Yes I will fix it as early as possible.

**Comment by Progi1984** [comment]
@mhasanshahid Why do you remove the Doughnut Chart ?

**Comment by mhasanshahid** [comment]
Because I dont have it in my local cloned version. I am under a testing phase, will update it.

**Comment by Progi1984** [comment]
@mhasanshahid  Hi Could you merge develop branch of PhpPresentation in your branch, please ? Thank you

**Comment by Progi1984** [comment]
@mhasanshahid The "AutoShape" or "Geometric shape" have been added in v1.0.0 (#545).

You can check the documentation : https://phpoffice.github.io/PHPPresentation/usage/shapes/autoshape.html
Or the sample file : https://github.com/PHPOffice/PHPPresentation/blob/develop/samples/Sample_21_AutoShape.php

(And fixes have been done in `develop` branch about broken charts).

Is it ok for you ?

**Pull request closed without merging**
