### PR TITLE
refactoring and reducing cyclomatic complexity

### PR DESCRIPTION
**Pull request by noodlesegg**

### CODE REVIEW

**Comment by Progi1984** [comment]
@noodlesegg Good job. Just a problem with PHPCS : https://travis-ci.org/PHPOffice/PHPPresentation/jobs/286132715#L602

And I will merge your work :)

**Comment by Progi1984** [comment]
@noodlesegg Hi, Good job. Need some fixes with PHPCS (https://travis-ci.org/PHPOffice/PHPPresentation/jobs/286132715#L602) and I will merge your work. Thank you.

**Comment by noodlesegg** [comment]
Hi @Progi1984, 

Many thanks, I used sublime text 3 editor should I install  [phpcs](https://github.com/SublimeLinter/SublimeLinter-phpcs) in order to fix the issues?

Thanks

**Comment by Progi1984** [comment]
@noodlesegg I don't know Sublime Text 3 but I think Yes :)

**Comment by Progi1984** [comment]
@noodlesegg Nearly.

Need one newline at end of file (src/PhpPresentation/PhpPresentation.php)
Link : https://travis-ci.org/PHPOffice/PHPPresentation/jobs/288601604#L627

**Pull request merged**
