### PR TITLE
#267 : Fixed the axis title in bar chart

### PR DESCRIPTION
**Pull request by Progi1984**
CC: #267

### CODE REVIEW

**Comment by pgee70** [comment]
sorry but i don't have enough knowledge of github to test this. i don't know how to pull a remote commit into my project - i installed this via packagist.  I the sample code works it should be fine.

**Comment by Progi1984** [comment]
@pgee70 I will help you :)

You go on the "Files changed" tab. You apply changes in your files from your vendor directory.

After that, you test your code and if, in your PPTX file, the axis title in bar chart is fixed, so it's ok.

**Comment by pgee70** [comment]
still having trouble.
I think i actioned those changes as requested. but the label position was not working:
using my code:
`oSeries = new PhpOffice\PhpPresentation\Shape\Chart\Series($data->activity . ' usage', $seriesData) ;
	$oSeries->setLabelPosition("inEnd") //PhpOffice\PhpPresentation\Shape\Chart\Series::LABEL_INSIDEEND)
		->setDlblNumFormat('0%');
	$oSeries->getFont()
		->setSize(18)
		->setColor(new PhpOffice\PhpPresentation\Style\Color( 'FFFFFFFF' ));`

the label is still showing in the outEnd position.
Thanks, if there is more you need any more testing data/ help contact me directly pgee at me dot com

**Comment by Progi1984** [comment]
@pgee70 I try to find the difference my pull request and your fix https://github.com/PHPOffice/PHPPresentation/issues/267#issuecomment-249421473 . But I can"t find.

Have you got some idea ?

**Pull request merged**
